### ISSUE TITLE
Pkg: Implement spacing system

### ISSUE THREAD

**Issue by xak** [SAP/techne#816] opened 2017-07-13 18:13 UTC
Base unit 4px

- Include named spacing system with logical steps up from the base unit
- Create function
- Add helpers
- Add documentation on site

Related to #748

**Comment by joseegm** [comment] 2017-07-14 11:56
Looking at:

https://github.com/SAP/techne/commit/a8524e7b84c41ccb362fc7e9447058463512ddf6#diff-dc446cd5ee41bbcf85b1778fa17c006aR18

```scss
$tn-spacing: (
   base: $tn-spacing--base,    //4
   xs: $tn-spacing--base * 2,  //8
   s: $tn-spacing--base * 4,   //12
   reg: $tn-spacing--base * 6, //24 (should match bottom margin default)
   m: $tn-spacing--base * 8,   //32
   l: $tn-spacing--base * 10,  //40
   xl: $tn-spacing--base * 25, //100
   xxl: $tn-spacing--base * 37 //148
   ) !default;
```

I recommend **avoiding using literal identifiers for the spacing.** The spacing system is about proportions: a < 2a < 3a, 4a > 2a, etc.

The developers cannot calculate the proportions using a literal system, they would **have to learn then by memory, not by logic**.

1. The system used on the design is simpler and logical, illustrated bellow
    ![image](https://user-images.githubusercontent.com/22662903/28210348-2ff7c05c-6897-11e7-8209-cc6745285e8b.png)

    I will recommend using only one notation: *a, 2a, 3a, 4a, etc* for the spacing.

2.  Having 2 systems available, means the components will get developed, ones with one system other with the other, in the worst case a mix of both. **That is not consistent** and the developer have to remember what each system is.

3. When using the same notation as the design, we don't have to "map" one system to the other, they just correspond exactly: *2a = tn-space(2)*

**Only one spacing notation, less margin for error**.

**This can be simpler and effective**.

**Comment by xak** [comment] 2017-07-14 14:11
The function does support number arguments that multiply as you describe.  That, however, should be the secondary use case. The design system should adhere to a modular scale that will not always be simple increments of 4, esp. when you get to large numbers like 100. Therefore the "keywords" should be used more often than the numbers. 

For example, the margins under block elements like `p`, `table`, `ul` will be 24px. Margins under form groups may be 40px, with margins under sections being 100px. These are fundamental measurements that will be repeated over and over again and bring a vertical rhythm to the site. You will see these core measurements regularly in the design so they are called out for that reason. These are more appropriate for defining how containers stack on top of each other. For the input example you show, the number arg is supported if fine-tuning needs to happen.

Having a controlled spacing hierarchy is as important as a controlled font hierarchy. We want to encourage common sizes and discourage arbitrary measurements. Again, the keywords are preferred, the numbers are available as a backup knowing that there will be cases where other dimensions are needed. There's no mapping needed, but yes, the devs may need a cheatsheet until they get used to it, just as they will need one for the fonts and colors.

Does that make sense? This system will continue to evolve so we can see how it works as it is applied.

**Comment by joseegm** [comment] 2017-07-14 14:40
@xak
I understand the need to have common spacing, **but that's shouldn't increase the learning curve.** 

**PLEASE NOTE: The spacing is given from the Visual Design, been able to map 1:1 that with the development is an increase in productivity.**

Again: 
```
2a = tn-space(2)
3a = tn-space(3)
4a = tn-space(4)
```
it is easier than
```
2a = tn-space(xs)
3a = tn-space(3) // there is not 3a literal equivalent
4a = tn-space(s)
```
That, **right there** exemplify the problems with the literal identifiers, **very clearly**.
 
This is contradictory on https://github.com/SAP/techne/issues/816#issuecomment-315369486
> There's no mapping needed, but yes, the devs may need a cheatsheet until they get used to it.

**If the developer need a cheatsheet, that's mapping right there.** The design proportions notation are not mapped directly to the literal identifiers.

**Other point**
There is no difference using always `tn-space(6)` all the time than `tn-space(reg)`. 

Even more problematic the developer have to **remember** that `p`, `table`, `ul` have `tn-space(reg)`

**Comment by xak** [comment] 2017-07-14 14:58
Thanks for your input, we'll see how it goes. I've had good luck with this set up in the past. If it proves burdensome, the number system is already in place to there's no real problem.

Again, the design should be using common sizes — 8, 12, 24, 40 — not random increments of 4. The same as the fonts, a dev should NEVER hardcode a font-size, they should ALWAYS use the approved sizes. This is the same, cementing the common sizes in code to encourage their use. The team will soon enough learn the hierarchy just as they will the fonts simply by looking at them.

It'll work, trust me.

**Comment by joseegm** [comment] 2017-07-18 07:35
@xak 
Your solution is not considering the pitfalls that I mentioned on https://github.com/SAP/techne/issues/816#issuecomment-315376728

They are real and they need to be addressed.

There is no valid technical reason for using literal spacing names, your arguments doesn't give a logic rationale behind.

This issues needs to be addressed before we need to change it all again like happened with the colors - https://github.com/SAP/techne/issues/765

**A technical solution/architecture must be proved in a POC before integrating in into the library.** Otherwise it just stays there and we have to drag the wrong solution because it is too late to change it.

Please review this again.

**Comment by xak** [comment] 2017-07-19 22:47
I haven't had a chance to talk with @LeoT7508 yet about this. It's really more his call so I'll get back to you.

**Comment by xak** [comment] 2017-07-21 01:25
I spoke with @LeoT7508 about this and he is fine with this notation esp. when we defining spacing for containers stacking on top of each other. That is the best use case ... labels have `base` bottom margins, cards will have `reg` between them and under them, sections will have `xl` bottom margins, etc. The hierarchy establishes a vertical rhythm.

An established hierarchy with easy-to-use names will also be easier for theming. If every spacing unit is defined in relation to a base unit, then the only modification possible is to change the base unit and the spacing will respond radically. The alternative then is to change each instance. If bottom margins are coded as `tn-space(5)` in multiple places and then a team decides they prefer a theme with a 24px bottom margin, each instance of the `tn-space(5)` must be modified to `(6)`. 

With a map of named spacing units, they can fine tune their theme more easily by changing the map itself.

```
$tn-spacing: (
    base: $tn-spacing--base,    //4
    xs: $tn-spacing--base * 2,  //8
    s: $tn-spacing--base * 3,   //12
    reg: $tn-spacing--base * 6, //24 (custom value)
    m: $tn-spacing--base * 8,   //40
    l: $tn-spacing--base * 10,  //100
    xl: $tn-spacing--base * 25, //148
);
```

If they want a 7px base unit, no problem. They can do that and still have better control over the end values ...

```
//spacing
$tn-spacing--base: 7px;
$tn-spacing: (
    base: $tn-spacing--base,    //7
    xs: $tn-spacing--base * 2,  //14
    s: $tn-spacing--base * 3,   //21
    reg: $tn-spacing--base * 4, //28
    m: $tn-spacing--base * 6,   //42
    l: $tn-spacing--base * 12,  //84
    xl: $tn-spacing--base * 20, //140
);
```

If we implement only a multiplication system (3a), the above change would require a huge number of overrides in the CSS for theming. We cannot guarantee that a theme will always use `5a` for the `reg` spacing. The Techne default **will** use `5a`, the examples above use `6a` and `4a` respectively.

Again, the spacing keywords are the **preferred** method and the design will reflect that. I see no problem with the overlap of `tn-space(5)` and `tn-space(reg)`. I can reference colors in CSS with all of these methods ...

```
color: red;
color: #00ff00;
color: rgb(0,0,255);
```

The named colors are a **convenience** just like ours here. There are only 140 colors that are named but I still have access to any rgb, hsl, or hex value I desire.

I cannot promise this will not change — the design system is still evolving — but it is manageable.

**Comment by joseegm** [comment] 2017-07-21 11:45
The only modification intended, tested and documented on the spacing feature is: **only have to change the base value** as described on https://github.com/SAP/techne/wiki/Spacing-Design-specs

Everything else, right now, is out of scope. And only waste development resources.

This feature's implementation as it is now: is focused on using the spacing feature from only SCSS.

That doesn't take in count: the main use of the library is CSS. **CSS usage is the main focus focus of the library.**

The visual rhythm is already implicit in the documented solution.

With all the above, 
**this solution is only worth the while when the following criteria has been meet:**
1. The spacing feature with the 2 modes as described on: https://github.com/SAP/techne/wiki/Spacing-Design-specs have a **CSS solution**, not only SCSS.
2. The visuals, which is the design step from where the final spacing comes out: **are provided in the proposed literal notation**.
3.  The components developed have a healthy 80-20 ratio: 80% literal values, 20% numeral values.

@xak 
**Can we agree to the above mentioned 3 points as acceptance criteria?**

**Comment by xak** [comment] 2017-07-21 20:11
I don't know what you mean by your last two comments but I'll create a `--compact` version of each component even though it will be confusing.

That presents two types of Cards (and other components) to choose from — regular and compact — so we may see a mix of the two when teams implement based on nothing more than a personal preference. That will **not** be a correct use of the `compact` library when the true use case is more of a theming concern. This also means that teams using `compact` globally will need to add an extra class to every component they use.

**Comment by xak** [comment] 2017-07-21 20:15
New issue created to address the card itself. This can be closed.

**Comment by LeoT7508** [comment] 2017-07-21 21:51
@joseegm @xak 

I agree with Zack on this one, we should make the theming global, not per component or from a visual side things will look broken if they have different components with different spacing on one page.

**Comment by joseegm** [comment] 2017-07-24 07:04
The feature is designed to be uses, per screen and details had been posted already on: https://github.com/SAP/techne/issues/827#issuecomment-316636672

Posting it here again for context:
The Spacing feature will be used mainly by CSS, not using the SCSS.

All components have to be implemented to adapt to a spacing class that can be present in a higher element in the DOM tree. The spacing options can be set at any level on the component hierarchy and the components bellow that will use the compact space.

The solution was first described at the request https://github.com/SAP/techne/issues/748
Was also designed at https://github.com/SAP/techne/issues/763, https://github.com/SAP/techne/issues/751

Example:
```html
<div class="tn-compact"> <!-- Spacing class set -->
    <div class="tn-cards"> <!-- Component adapt the spacing -->
        <div class="tn-card"> <!-- Component adapt the spacing --> 
            <!-- . . . -->
        </div>
    </div>
</div>
```

That's is already implemented on
https://techne-alpha.firebaseapp.com/components/structure/spacing

**Comment by joseegm** [comment] 2017-07-24 08:32
@xak The points you don't understand:

2. The final visuals will be represented using a similar notation as:
    ![image](https://user-images.githubusercontent.com/22662903/28514572-cb655778-705a-11e7-8f78-ea739cdeedb8.png)

3. 80% of the spacing should be set using the literal values and not the numerical ones.

**Comment by joseegm** [comment] 2017-07-24 12:45
I'll put this back to "in process". The feature implementation doesn't work as designed.

**Comment by xak** [comment] 2017-07-26 17:02
Feedback from the Backoffice developer indicates that the solution as design is sufficient for an MVP. No further changes are needed at this time. As we gather feedback from alpha and beta releases we can revisit this.

It is more important to focus on the default Techne theme now. Advanced features can be discussed holistically at a later time.

**Closed** 2017-07-26 17:03 UTC
